name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.10

      - name: Retrieve Version
        id: get_version
        run: |
          VERSION_FILE="version.go"
          OLD_VERSION=$(grep -oP 'const VERSION = "\K[^"]+' "$VERSION_FILE")
          echo "::set-output name=old_version::$OLD_VERSION"
      
      - name: Increment Version
        id: increment_version
        run: |
          VERSION_FILE="cmd/rogue/pkg/sysinfo/version.go"
          OLD_VERSION="${{ steps.get_version.outputs.old_version }}"
          IFS='.' read -r -a VERSION_PARTS <<< "$OLD_VERSION"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          PATCH="${VERSION_PARTS[2]}"

          if [ "$PATCH" -eq 99 ]; then
            PATCH=0
            if [ "$MINOR" -eq 9 ]; then
              MINOR=0
              MAJOR=$((MAJOR + 1))
            else
              MINOR=$((MINOR + 1))
            fi
          else
            PATCH=$((10#$PATCH + 1))
          fi
          PATCH=$(printf "%02d" "$PATCH")
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "::set-output name=new_version::$NEW_VERSION"

          sed -i "s/const VERSION = \"$OLD_VERSION\"/const VERSION = \"$NEW_VERSION\"/" "$VERSION_FILE"
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgio2.0-cil-dev libgio2.0-cil-dev libgstreamer1.0-dev

      - name: Build
        id: build
        run: |
          make

      - name: Create Directory and Move Files
        run: |
          NEW_VERSION="${{ steps.increment_version.outputs.new_version }}"
          mkdir -p build/$NEW_VERSION
          mv rogue.tgz build/$NEW_VERSION/rogue$NEW_VERSION.tgz
          mv C25_APP* build/$NEW_VERSION

      - name: Pause Execution
        run: sleep infinity
