name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on any tag that starts with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build or compilation steps here

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by GitHub Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: ./test.go # Specify the path to your artifact here
